package ro.trenulmeu.mobile.models;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import ro.trenulmeu.mobile.models.DataBaseStatusDao;
import ro.trenulmeu.mobile.models.TrainOperatorDao;
import ro.trenulmeu.mobile.models.TrainTypeDao;
import ro.trenulmeu.mobile.models.TrainServiceDao;
import ro.trenulmeu.mobile.models.TrainPriceDao;
import ro.trenulmeu.mobile.models.StationDao;
import ro.trenulmeu.mobile.models.TrainDao;
import ro.trenulmeu.mobile.models.TrainAvailabilityDao;
import ro.trenulmeu.mobile.models.TrainPathDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        DataBaseStatusDao.createTable(db, ifNotExists);
        TrainOperatorDao.createTable(db, ifNotExists);
        TrainTypeDao.createTable(db, ifNotExists);
        TrainServiceDao.createTable(db, ifNotExists);
        TrainPriceDao.createTable(db, ifNotExists);
        StationDao.createTable(db, ifNotExists);
        TrainDao.createTable(db, ifNotExists);
        TrainAvailabilityDao.createTable(db, ifNotExists);
        TrainPathDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        DataBaseStatusDao.dropTable(db, ifExists);
        TrainOperatorDao.dropTable(db, ifExists);
        TrainTypeDao.dropTable(db, ifExists);
        TrainServiceDao.dropTable(db, ifExists);
        TrainPriceDao.dropTable(db, ifExists);
        StationDao.dropTable(db, ifExists);
        TrainDao.dropTable(db, ifExists);
        TrainAvailabilityDao.dropTable(db, ifExists);
        TrainPathDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(DataBaseStatusDao.class);
        registerDaoClass(TrainOperatorDao.class);
        registerDaoClass(TrainTypeDao.class);
        registerDaoClass(TrainServiceDao.class);
        registerDaoClass(TrainPriceDao.class);
        registerDaoClass(StationDao.class);
        registerDaoClass(TrainDao.class);
        registerDaoClass(TrainAvailabilityDao.class);
        registerDaoClass(TrainPathDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
