package ro.trenulmeu.mobile.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DataBaseStatus".
 */
public class DataBaseStatus {

    private Long id;
    private java.util.Date Date;
    private Boolean NeedDeploy;
    private java.util.Date ValidFrom;
    private java.util.Date ValidTo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DataBaseStatus() {
    }

    public DataBaseStatus(Long id) {
        this.id = id;
    }

    public DataBaseStatus(Long id, java.util.Date Date, Boolean NeedDeploy, java.util.Date ValidFrom, java.util.Date ValidTo) {
        this.id = id;
        this.Date = Date;
        this.NeedDeploy = NeedDeploy;
        this.ValidFrom = ValidFrom;
        this.ValidTo = ValidTo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDate() {
        return Date;
    }

    public void setDate(java.util.Date Date) {
        this.Date = Date;
    }

    public Boolean getNeedDeploy() {
        return NeedDeploy;
    }

    public void setNeedDeploy(Boolean NeedDeploy) {
        this.NeedDeploy = NeedDeploy;
    }

    public java.util.Date getValidFrom() {
        return ValidFrom;
    }

    public void setValidFrom(java.util.Date ValidFrom) {
        this.ValidFrom = ValidFrom;
    }

    public java.util.Date getValidTo() {
        return ValidTo;
    }

    public void setValidTo(java.util.Date ValidTo) {
        this.ValidTo = ValidTo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
